<?php

/**
 * @file
 * Code for the darty_traitement_form
 */

/*
 * ***************** hook_form_alter
 */
function darty_form_traitement_form_alter(&$form, &$form_state, $form_id) {
    switch($form_id) {
        case 'article_node_form':

            /*$form['actions']['draft'] = array(
                '#type' => 'submit',
                '#value' => t('Save draft'),
                '#weight' => '9',
                '#submit' => array('__save_draft_submit'),
                '#validate' => array('__save_draft_validate'),
                '#attributes' => array(
                    'class' => array('cancel'), // add the class cancel will skip any clientside validation
                ),
                //'limit_validation_errors' => array(), // this should be enough to skip validation however does not work for me
            );*/

            break;
    }
}

/*
function __save_draft_validate($form, &$form_state) {
    // Set as unpublished.
    $form_state['values']['status'] = 0;
    // Force validation.
    $errors = &drupal_static('form_set_error', NULL, TRUE);

}

function __save_draft_submit($form, &$form_state) {
    // clear error messsages
    drupal_get_messages();
    // save the node
    node_form_submit($form, $form_state);
    $form_state['redirect'] = 'node/'.$form_state['nid'].'/edit';
}
 * 
 */