<?php

/**
 * @file
 * Main file for the Save Draft module, which adds a 'Save as draft' button to content types.
 */

/**
 * Implements hook_permission().
 */
function darty_brouillon_permission() {
  return array(
    'save draft' => array(
      'title' => t('Sauvegarder un contenu sans publier'),
      'description' => t('Autoriser les utilisateur à sauvegarder de contenu sans les publié.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function darty_brouillon_form_node_form_alter(&$form, &$form_state) {
  if (user_access('save draft')) {
    $form['options']['#title'] = t('Promotion settings');
    $form['options']['#attributes']['class'] = array('node-promotion-options');
    $form['options']['#attached'] = array(
      'js' => array(
        'vertical-tabs' => drupal_get_path('module', 'darty_brouillon') . '/darty_brouillon.js',
      ),
    );
    $form['options']['status'] = false;
    if (empty($form['#validate'])) {
      $form['#validate'] = array();
    }
    array_unshift($form['#validate'], 'darty_brouillon_validate');
    if (isset($form['nid']['#value'])) {
      if ($form['#node']->status == 1) {
        $form['actions']['draft'] = array(
          '#type' => 'submit',
          '#class' => 'form-submit',
          '#value' => t('Dépublier'),
          '#weight' => '9',
          '#submit' => array('darty_brouillon_submit')
        );
        $form['actions']['submit']['#value'] = t('Sauvegarder');
      }
      else {
        $form['actions']['draft'] = array(
          '#type' => 'submit',
          '#class' => 'form-submit',
          '#value' => t('Sauvegarder'),
          '#weight' => '0',
          '#submit' => array('darty_brouillon_submit')
        );
        $form['actions']['submit']['#value'] = t('Publier');
      }
    }
    else {
      $form['actions']['draft'] = array(
        '#type' => 'submit',
        '#class' => 'form-submit',
        '#value' => t('Sauvegarder'),
        '#weight' => '9',
        '#submit' => array('darty_brouillon_submit')
      );
      $form['actions']['submit']['#value'] = t('Publier');
    }
  }
}

/**
 * Handles save draft form validation
 */
function darty_brouillon_validate($form, &$form_state) {
  // Set the node to be published or unpublished depending on which button was
  // clicked.
  if ($form_state['triggering_element']['#value'] == $form['actions']['draft']['#value']) {
    drupal_get_messages();  // clear error messsages
    $form_state['values']['status'] = 0; // Set as unpublished.
    $errors = &drupal_static('form_set_error', NULL, TRUE);
  }
  elseif ($form_state['triggering_element']['#value'] == $form['actions']['submit']['#value']) {
    $form_state['values']['status'] = 1;
  }
}

/**
 * Handles save draft form submission
 */
function darty_brouillon_submit($form, &$form_state) {
  node_form_submit($form, $form_state);
}
